version: "3.7"
services:
  db:
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: slack_copy_app
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
