openapi: 3.0.0
info:
  title: Slack-Copy-App
  version: 0.0.1
servers:
- url: /
paths:
  /users:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                title: GetUsersResponse
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'

    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DraftUser'
      responses:
        201:
          description: OK
          headers:
            Location:
              schema:
                type: string
                description: 作成したリソースのURI

components:
  schemas:
    DraftUser:
      type: object
      properties:
        name:
          description: ユーザー名
          type: string
        email:
          description: メールアドレス
          type: string
      required:
        - name
        - email

    User:
      type: object
      properties:
        id:
          description: ユーザー識別子
          type: string
        name:
          description: ユーザー名
          type: string
        email:
          description: メールアドレス
          type: string
      required:
        - id
        - name
        - email
