openapi: 3.0.0
info:
  title: Slack-Copy-App
  version: 0.0.1
servers:
- url: /
paths:
  /ping:
    get:
      operationId: pingGET
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
          description: OK
      x-openapi-router-controller: DefaultController
      x-openapi-router-service: DefaultService
components:
  schemas:
    Pong:
      example:
        pong: true
      properties:
        pong:
          type: boolean
      type: object
